---
- op: replace
  path: /spec/template/spec/sources/1/repoURL
  value: https://github.com/redhat-appstudio-qe/infra-deployments.git
- op: replace
  path: /spec/template/spec/sources/1/targetRevision
  value: preview-KFLUXUI-901-2-ujzg
