---
- op: replace
  path: /spec/source/repoURL
  value: https://github.com/redhat-appstudio-qe/infra-deployments.git
- op: replace
  path: /spec/source/targetRevision
  value: preview-KAR-770_update_vector_image_to_0_52_0-oorc
