---
- op: replace
  path: /spec/source/repoURL
  value: https://github.com/redhat-appstudio-qe/infra-deployments.git
- op: replace
  path: /spec/source/targetRevision
  value: preview-KONFLUX-12175-upgrade-pipelines-nightly-hdxn
