---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/redhat-appstudio-qe/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-bump-etcd-shield-staging-ebib
