apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- https://github.com/konflux-ci/project-controller/config/default?ref=e66377666a632ba78f9f9f09519dfe484ad72b34

images:
- name: konflux-project-controller
  newName: quay.io/konflux-ci/project-controller
  newTag: e66377666a632ba78f9f9f09519dfe484ad72b34

namespace: project-controller
