apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- https://github.com/konflux-ci/project-controller/config/default?ref=675619443aed1182fef5f647a3f84570980e5d54

images:
- name: konflux-project-controller
  newName: quay.io/konflux-ci/project-controller
  newTag: 675619443aed1182fef5f647a3f84570980e5d54

namespace: project-controller
