apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: multi-platform-controller

resources:
- ../../base/common
- host-config.yaml
- external-secrets.yaml
- https://github.com/konflux-ci/multi-platform-controller/deploy/operator?ref=318fd4ce48ab3453e0368dcefa4e26606462bfc9
- https://github.com/konflux-ci/multi-platform-controller/deploy/otp?ref=318fd4ce48ab3453e0368dcefa4e26606462bfc9

components:
  - ../../k-components/manager-resources

images:
- name: multi-platform-controller
  newName: quay.io/konflux-ci/multi-platform-controller
  newTag: 318fd4ce48ab3453e0368dcefa4e26606462bfc9
- name: multi-platform-otp-server
  newName: quay.io/konflux-ci/multi-platform-controller-otp-service
  newTag: 318fd4ce48ab3453e0368dcefa4e26606462bfc9

patches:
  - path: manager_resources_patch.yaml
