resources:
- internal_service_request_role.yaml
- internal_service_request_role_binding.yaml
- internal_service_request_service_account.yaml
- internal_service_service_account_token.yaml
- internal-services.yaml
- https://github.com/konflux-ci/internal-services/config/crd?ref=b7064f74538841191441612d2188f8c050d41c34

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: internal-services
