resources:
- internal_service_request_role.yaml
- internal_service_request_role_binding.yaml
- internal_service_request_service_account.yaml
- internal_service_service_account_token.yaml
- internal-services.yaml
- https://github.com/konflux-ci/internal-services/config/crd?ref=e51c1be3fb161a424efb5db1a974fd2bfecbb006

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: internal-services
