apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: multi-platform-controller

resources:
- common
- rbac
- https://github.com/konflux-ci/multi-platform-controller/deploy/operator?ref=02927109412bd7f1d70c2494c71bc6c272a99378
- https://github.com/konflux-ci/multi-platform-controller/deploy/otp?ref=02927109412bd7f1d70c2494c71bc6c272a99378


images:
- name: multi-platform-controller
  newName: quay.io/konflux-ci/multi-platform-controller
  newTag: 02927109412bd7f1d70c2494c71bc6c272a99378
- name: multi-platform-otp-server
  newName: quay.io/konflux-ci/multi-platform-controller-otp-service
  newTag: 02927109412bd7f1d70c2494c71bc6c272a99378
