apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: multi-platform-controller

resources:
- common
- rbac
- https://github.com/konflux-ci/multi-platform-controller/deploy/operator?ref=b721db4c4ba594cbaec462f329c1bc295bece871
- https://github.com/konflux-ci/multi-platform-controller/deploy/otp?ref=b721db4c4ba594cbaec462f329c1bc295bece871


images:
- name: multi-platform-controller
  newName: quay.io/konflux-ci/multi-platform-controller
  newTag: b721db4c4ba594cbaec462f329c1bc295bece871
- name: multi-platform-otp-server
  newName: quay.io/konflux-ci/multi-platform-controller-otp-service
  newTag: b721db4c4ba594cbaec462f329c1bc295bece871
