apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: multi-platform-controller

resources:
- common
- rbac
- https://github.com/konflux-ci/multi-platform-controller/deploy/operator?ref=b3e3e21be1777226f81e523c69576af516ad106e
- https://github.com/konflux-ci/multi-platform-controller/deploy/otp?ref=b3e3e21be1777226f81e523c69576af516ad106e


images:
- name: multi-platform-controller
  newName: quay.io/konflux-ci/multi-platform-controller
  newTag: b3e3e21be1777226f81e523c69576af516ad106e
- name: multi-platform-otp-server
  newName: quay.io/konflux-ci/multi-platform-controller-otp-service
  newTag: b3e3e21be1777226f81e523c69576af516ad106e
