apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/konflux-ci/notification-service/config/default?ref=616c724a820a3763a7b8273604375bc1dafcd7d7

images:
  - name: quay.io/konflux-ci/notification-service
    newName: quay.io/konflux-ci/notification-service
    newTag: 616c724a820a3763a7b8273604375bc1dafcd7d7

namespace: notification-controller

patches:
  - path: topic_region_add.yaml
    target:
      name: notification-controller-controller-manager
      kind: Deployment
