apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/konflux-ci/notification-service/config/default?ref=035562174882df6261beec3eec46f2f481900403

images:
  - name: quay.io/konflux-ci/notification-service
    newName: quay.io/konflux-ci/notification-service
    newTag: 035562174882df6261beec3eec46f2f481900403

namespace: notification-controller

patches:
  - path: topic_region_add.yaml
    target:
      name: notification-controller-controller-manager
      kind: Deployment
