apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/konflux-ci/project-controller/config/default?ref=9b28bd6e06a24c91b05c17c80f8a78abcb28b095

images:
- name: konflux-project-controller
  newName: quay.io/konflux-ci/project-controller
  newTag: 9b28bd6e06a24c91b05c17c80f8a78abcb28b095

namespace: project-controller
