apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/konflux-ci/project-controller/config/default?ref=f016abb046fc168c3f50940d5cea3e031889e70b

images:
- name: konflux-project-controller
  newName: quay.io/konflux-ci/project-controller
  newTag: f016abb046fc168c3f50940d5cea3e031889e70b

namespace: project-controller
