apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/konflux-ci/project-controller/config/default?ref=45ae9a64b604376baa009f09a7c3d71c9deb456a

images:
- name: konflux-project-controller
  newName: quay.io/konflux-ci/project-controller
  newTag: 45ae9a64b604376baa009f09a7c3d71c9deb456a

namespace: project-controller
